### ISSUE TITLE
Deep Learning Research

### ISSUE THREAD

**Issue by KokeCacao** [JarrettR/Stagger#1]
Hi JarrettR,

I am currently using some of Stagger to complete my research in this two_bar system w/ Computer Vision approach. In fact, I have fixed some issues and made the code more readable. Do you want to cooperate with me if you are interested?

Best,
Hanke Chen

**Comment by JarrettR** [comment]
Hey,

I'd welcome pull requests!

Might take me a while to get to reviewing them, but I will eventually
